config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, :controllers => {:registrations => "custom_devise/registrations"}

  root 'search#index'
  resources :users

  namespace :search do
    get '/', action: :index, as: :index
  end

  namespace :baskets do
    get '/', action: :index, as: :index
    post :send_to_basket
    post :clear_basket
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  DEVISE_MODULES = %i[database_authenticatable registerable recoverable rememberable validatable trackable]

  devise(*DEVISE_MODULES)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  protected

  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:api_token])
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :get_api_key

  def index
    response = PartsSoft::Commands::Baskets.new(:get, @api_key).call

    @collection = response.fetch(:data) if response.success?
  end

  def send_to_basket
    return if params[:oem].blank? || params[:api_hash].blank?

    response = PartsSoft::Commands::Baskets.new(
      :post,
      @api_key,
      qnt: params[:qnt],
      oem: params[:oem],
      detail_name: params[:detail_name],
      api_hash: params[:api_hash],
    ).call

    redirect_to baskets_index_path if response.success?
  end

  def clear_basket
    response = PartsSoft::Commands::BasketsClear.new(:post, @api_key).call

    redirect_to baskets_index_path if response.success?
  end

  protected

  def get_api_key
    @api_key = current_user.api_token
  end
end

app/controllers/custom_devise/registrations_controller.rb
class CustomDevise::RegistrationsController < Devise::RegistrationsController
  def sign_up_params
    super.tap do |whitelisted|
      whitelisted[:api_token] = params[:user][:api_token]
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:q].present? && !params[:q].empty?
      @search = SearchService.new(
        params.slice(:q, :brand).merge(user_id: current_user.id).to_unsafe_h
      ).search
    end

    render 'search/index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user

  def edit
  end

  def update
    @user.update(user_params)
  end

  protected

  def load_user
    @user = current_user
  end

  def user_params
    UserPermit.new(current_user).permit(params.require(:user))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/baskets/index.html.haml
%h1
  Корзина

.objects-container
  %table.ar-table-simple
    %thead
      %tr
        %th
          Бренд
        %th
          Номер
        %th
          Название
        %th
          Цена

    %tbody
      - if @collection.present?
        - @collection.each do |obj|
          %tr
            %th
              = obj['make_name']
            %th
              = obj['oem']
            %th
              = obj['detail_name']
            %th
              = obj['cost']

app/views/layouts/application.html.haml
%html
  %head
    %title
      PartsSoft
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all'

    %body
      %p.notice= notice
      %p.alert= alert

      - if user_signed_in?
        .container
          .header
            .header-left
              Добро пожаловать #{current_user.first_name.present? || current_user.email} !
              = button_to "Выйти из аккаунта", destroy_user_session_path, method: :delete
            .header-right
              = link_to "Редактировать профиль", edit_user_path(current_user)
              %br
              = link_to "Главная", root_path
              %br
              = link_to "Корзина", baskets_index_path
          = yield
      - else
        = yield

app/views/search/_results_by_default.html.haml
%h1
  Результаты поиска по номеру

.objects-container
  %table.ar-table-simple
    %thead
      %tr
        %th
          Бренд
        %th
          Номер
        %th
          Название

    %tbody
      - search.each do |obj|
        %tr
          %th
            = obj['brand']
          %th
            = obj['number']
          %th
            = obj['des_text']

app/views/search/_results_with_baskets.html.haml
%h1
  Результаты поиска по номеру и бренду

.objects-container
  %table.ar-table-simple
    %thead
      %tr
        %th
          Бренд
        %th
          Номер
        %th
          Название
        %th
          Кол
        %th
          Цена
        %th
          Цена с наценкой
        %th
          Срок доставки Мин
        %th
          Срок доставки Макс
        %th
          Кол. для заказа
        %th
          Добавить в корзину

    %tbody
      - search.each do |obj|
        %tr
          %th
            = obj['make_name']
          %th
            = obj['oem']
          %th
            = obj['detail_name']
          %th
            = obj['qnt']
          %th
            = obj['cost']
          %th
            = '150' # Не понял где взять цену с наценкой
          %th
            = obj['min_delivery_day']
          %th
            = obj['max_delivery_day']
          %th
            - timestamp = rand(10**10..10**15).to_s
            = form_with url: baskets_send_to_basket_path, id: "send-to-basket-form-#{timestamp}" do
              = hidden_field_tag :oem, obj['oem'].to_s
              = hidden_field_tag :api_hash, obj['hash_key'].to_s
              = hidden_field_tag :detail_name, obj['detail_name'].to_s
              = number_field_tag :qnt, 0
          %th
            = button_tag 'Добавить в корзину',  form: "send-to-basket-form-#{timestamp}"

app/views/search/index.html.haml
:ruby
  brand = params[:brand]
  search_request = params[:q]

.search_form
  = form_with url: [:search, :index], method: :get,  id: 'search-form', data: { remote: true } do
    .form-group
      = text_field_tag :q, search_request, placeholder: 'Введите номер', class: 'search-field'
    .form-group
      = label_tag 'brand:'
      = select_tag :brand, options_for_select([[''], ['DOLZ']]), placeholder: ''

    = button_tag 'Поиск'

- if @search.present? && brand.present?
  = render partial: 'results_with_baskets', locals: { search: @search }
- elsif @search.present?
  = render partial: 'results_by_default', locals: { search: @search }

app/views/users/edit.html.haml
%h2
  Edit user

= form_with model: @user do |f|
  .field
    = f.label :email
    %br
    = f.email_field :email, autofocus: true, autocomplete: "email", value: @user.email

  .field
    = f.label :api_token
    %br
    = f.text_field :api_token, autocomplete: "api-token", value: @user.api_token

  .actions
    = f.submit "Save"